# Main commands
# ~~~~~~~~~~~~~

# Generates all tinantas supported by the program and writes them to stdout.
create_tinantas:
	cargo run --release --bin create_tinantas


# Generates all krdantas-prAtipadikas supported by the program and writes them to stdout.
create_krdantas:
	cargo run --release --bin create_krdantas


# Unit tests
# ~~~~~~~~~~

# Runs all unit tests in the crate.
unit_tests:
	cargo test --lib

# Generates a simple coverage report and writes it to disk as an HTML file.
coverage:
	cargo llvm-cov --html


# Integration tests
# ~~~~~~~~~~~~~~~~~

# Generates all tinantas supported by the program and writes them to disk.
create_test_files:
	cargo build --release
	./target/release/create_tinantas --prayoga kartari > test-files/tinantas-basic-kartari.csv
	# ./target/release/create_tinantas --sanadi Ric --prayoga kartari > test-files/tinantas-Ric-kartari.csv
	# ./target/release/create_tinantas --sanadi san --prayoga kartari > test-files/tinantas-san-kartari.csv
	./target/release/create_tinantas --prayoga karmani > test-files/tinantas-basic-karmani.csv
	./target/release/create_krdantas --krt ktvA > test-files/krdantas-ktvA.csv
	./target/release/create_krdantas --krt kta > test-files/krdantas-kta.csv

# Runs a full evaluation over all forms generated by vidyut-prakriya. `hash` is
# the SHA-256 hash of the test file. We use `hash` to verify test file
# integrity and ensure that our test cases are stable.
#
# NOTE: test files might contain invalid forms. Our goal with this test is
# simply to confirm that the system hasn't changed in unexpected ways.
test_all:
	cargo build --release
	./target/release/test_tinantas \
		--test-cases test-files/tinantas-basic-kartari.csv \
	    --hash "08838cc8855cf62ab3102a757f90ce02c19dfc263bb7ece396420e76cc19f720"
	./target/release/test_tinantas \
		--test-cases test-files/tinantas-basic-karmani.csv \
	    --hash "fa3278773b0847c3f36d50afe6b7938f19af2e8c6c7cfd4d06f45fddc39f81b4"
	./target/release/test_krdantas \
		--test-cases test-files/krdantas-ktvA.csv \
	    --hash "dce95d8830c8c94009114c01ce543a784d88f1e2698fcba3415896157395dd69"
	./target/release/test_krdantas \
		--test-cases test-files/krdantas-kta.csv \
	    --hash "ca88235098410ee46c92efa458165338b055fe6fd1bb43416f3df859c5c4652c"

test_subantas:
	# Work-in-progress tests for subantas.
	./target/release/test_subantas


# Performance
# ~~~~~~~~~~~

# Profiles the program's execution time on OSX. This command will probably not
# work on other operating systems.
profile-time-osx:
	cargo instruments -t time --release --bin create_test_file


# Other
# ~~~~~

# Generates project docs and opens them in your default browser.
docs:
	cargo doc --no-deps --open
