mod abhyasasya;
mod ac_sandhi;
mod angasya;
mod ardhadhatuka;
pub mod ashtadhyayi;
mod asiddhavat;
mod atidesha;
mod atmanepada;
mod char_view;
pub mod constants;
mod dhatu_gana;
mod dhatu_karya;
pub mod dhatupatha;
mod dvitva;
mod filters;
mod it_agama;
mod it_samjna;
mod la_karya;
mod operators;
pub mod prakriya;
mod samjna;
mod samprasarana;
mod sanadi;
pub mod sounds;
mod stem_gana;
mod sup_adesha;
pub mod term;
mod tin_pratyaya;
mod tripadi;
mod vikarana;
