mod abhyasasya;
mod ac_sandhi;
mod angasya;
mod ardhadhatuka;
mod asiddhavat;
mod atidesha;
mod atmanepada;
mod char_view;
mod dhatu_gana;
mod dhatu_karya;
// TODO
mod dvitva;
mod filters;
mod it_agama;
mod it_samjna;
mod la_karya;
mod operators;
mod samjna;
mod samprasarana;
mod sanadi;
mod stem_gana;
mod sup_adesha;
mod tin_pratyaya;
mod tripadi;
mod vikarana;

pub mod ashtadhyayi;
pub mod constants;
pub mod dhatupatha;
pub mod prakriya;
pub mod sounds;
pub mod term;
